# a = 1
# b = 8
# c = 3
# d = 6
# f = 2
# max = a
# if b > max: max = b
# if c > max: max = c
# if d > max: max = d
# if f > max: max = f

# print(max)


# Numbers = [1,8,2,6,3]
# print( max(Numbers))



# numbers = [1, 8, 3, 2, 6]
# size = 5

# first = numbers[0]
# second = numbers[0]

# if numbers[1] > first:
#     first = numbers[1]
# else:
#     second = numbers[1]

# current_index = 2
# while current_index < size:
#     if numbers[current_index] > first:
#         second = first
#         first = numbers[current_index]
#     elif numbers[current_index] > second:
#         second = numbers[current_index]
#     current_index += 1

# print(second)




# a = 1
# b = 4
# c = 6
# d = 9
# e = 3

# max = a

# if max < b: max = b
# if max < c: max = c
# if max < d: max = d
# if max < e: max = e

# print(max)



# numbers = [1, 6, 4, 3, 8]
# size = 5

# frist = numbers[0]
# second = numbers[0]

# if numbers[1] > frist:
#     frist = numbers[1] 
# else:
#     second = numbers[1]

#     current_index = 2

# current_index = 2
# while current_index < size:
#     if numbers[current_index] > frist:
#         second = frist
#         frist = numbers[current_index]
#     elif numbers[current_index] > second:
#         second = numbers[current_index]
#     current_index += 1

# print(second)



a = 5
b = 1.554
c = 'Hello World'
print(f"{a} - {b} - {c}")